title: Jangwoon Sung
email: jwsung94@gmail.com
description: >
  Postdoctoral researcher 
url: "https://jsung1994.github.io"
baseurl: ""   # user site면 "" / project site면 "/repo-name"

theme: minima

# minima에서 상단 메뉴로 노출할 페이지
header_pages:
  - index.markdown
  - about.markdown

# 소셜 링크(원하는 것만 남겨)
minima:
  social_links:
    # - { platform: github,  user_url: "https://github.com/jsung1994" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/j-sung-kr/" }

# (선택) 날짜 형식
date_format: "%Y-%m-%d"